---
# --- AWX/Tower objects ---
organization_id: 6
project_id: 3332
project_branch: "feature/single-template"

# --- Credentials (IDs) ---
# Base credential by region
region_credentials:
  EMEA: 21
  AMER: 102
  APAC: 26

# Override credential when product implies a special zone
zone_credentials:
  dmz: 24
  lbi: 146

# --- Instance Groups (by NAME) ---
region_instance_groups:
  EMEA: "MiddlewareFR"
  AMER: "iv2amer"
  APAC: "iv2apac"

# --- Product family -> playbook + inventory ini ---
# NOTE: ini paths are relative to the project root in SCM.
product_map:
  apache:
    playbook: "elastic-iv2-apache.yml"
    ini: "inventories/apache.ini"
  iis:
    playbook: "elastic-iv2-iis.yml"
    ini: "inventories/iis.ini"
  jboss:
    playbook: "elastic-iv2-jboss.yml"
    ini: "inventories/jbossap.ini"
  sso:
    playbook: "elastic-iv2-sso.yml"
    ini: "inventories/sso.ini"
  tomcat:
    playbook: "elastic-iv2-tomcat.yml"
    ini: "inventories/tomcat.ini"
  was:
    playbook: "elastic-iv2-was.yml"
    ini: "inventories/was.ini"
  weblogic:
    playbook: "elastic-iv2-weblogic.yml"
    ini: "inventories/weblogic.ini"
