---
project_branch: "feature/single-template"

ini_files:
  - "apache.ini"
  - "iis.ini"
  - "jbosseap.ini"
  - "sso.ini"
  - "tomcat.ini"
  - "was.ini"
  - "weblogic.ini"

region_credentials:
  emea: 21
  amer: 102
  apac: 26
  dmzi: 24
  lbi: 146

selected_cred_id: "{{ region_credentials[region] }}"

playbook_to_run:
  - "elastic-iv2-apache.yml"
  - "elastic-iv2-iis.yml"
  - "elastic-iv2-jboss.yml"
  - "elastic-iv2-sso.yml"
  - "elastic-iv2-tomcat.yml"
  - "elastic-iv2-was.yml"
  - "elastic-iv2-weblogic.yml"

launch_limit: "dev:children:emea:children"

sso_template_id: 3333
organization_id: 6
scm_credential_id: "Middleware - Bitbucket"
project_id: 3332

instance_groups_id:
  EMEA: 1
  AMER: 6
  APAC: 7
